export {default as Activities} from "./activities"
export {default as Home} from "./home"
export {default as Museums} from "./museums"
export {default as SignIn} from "./signin"
export {default as VisitTogether} from "../components/museum/BuyTickets"